<?php

/**
 * PluginsfGuardObjectAuthorInfoTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfDoctrineGuardObjectAuthorInfoPlugin
 * @subpackage lib.model
 * @author     Daniel Ancuta <whisller@gmail.com>
 */
class PluginsfGuardObjectAuthorInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardObjectAuthorInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardObjectAuthorInfo');
    }
}