<?php

/**
 * PluginsfGuardObjectAuthorInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardObjectAuthorInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardObjectAuthorInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardObjectAuthorInfo');
    }
}