<?php

/**
 * PluginsfGuardObjectAuthorInfo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfDoctrineGuardObjectAuthorInfoPlugin
 * @subpackage lib.model
 * @author     Daniel Ancuta <whisller@gmail.com>
 */
abstract class PluginsfGuardObjectAuthorInfo extends BasesfGuardObjectAuthorInfo
{

}